name: emojivoto-voting-svc
# Change this to the id given to you by "riser apps new emojivoto-voting-svc"
id: 4cb64c40
image: buoyantio/emojivoto-voting-svc
deploy:
  replicas: 1
environment:
  GRPC_PORT: 8080
expose:
  containerPort: 8080