name: emojivoto-emoji-svc
# Change this to the id given to you by "riser apps new emojivoto-emoji-svc"
id: a04eaf60
image: buoyantio/emojivoto-emoji-svc
deploy:
  replicas: 1
environment:
  GRPC_PORT: 8080
expose:
  containerPort: 8080
