name: emojivoto
# TODO: Change this to the id given to you by "riser apps new emojivoto"
id: 6dbebf2a
image: buoyantio/emojivoto-web
environment:
  WEB_PORT: 80
  EMOJISVC_HOST: emojivoto-emoji-svc.apps.svc.cluster.local:8080
  VOTINGSVC_HOST: emojivoto-voting-svc.apps.svc.cluster.local:8080
  INDEX_BUNDLE: dist/index_bundle.js
expose:
  containerPort: 80
