name: emojivoto
# Change this to the id given to you by "riser apps new emojivoto"
id: b1200585
# Docker image will be convention based and likely removed
image: buoyantio/emojivoto-web
deploy:
  replicas: 3
environment:
  WEB_PORT: 80
  EMOJISVC_HOST: emojivoto-emoji-svc.apps.svc.cluster.local:8080
  VOTINGSVC_HOST: emojivoto-voting-svc.apps.svc.cluster.local:8080
  INDEX_BUNDLE: dist/index_bundle.js
expose:
  containerPort: 80

# Stage Overrides
stages:
  dev:
    deploy:
      replicas: 1